version: '3.8'

services:
  db:
    image: postgres:13
    container_name: condostock_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}         # Lê do .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Lê do .env
      POSTGRES_DB: ${POSTGRES_DB}             # Lê do .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - condo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: condostock_api
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL} # Lê do .env
      JWT_SECRET: ${JWT_SECRET}     # Lê do .env
    command: /bin/sh -c "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run start:dev"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - condo-network

  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: condostock_web
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL} # Lê do .env
    command: npm run dev -- --host 
    networks:
      - condo-network

volumes:
  pgdata:

networks:
  condo-network:
    driver: bridge