version: '3.8'

services:
  # Serviço do Backend (NestJS)
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app           # Mapeia sua pasta local para dentro do container (Hot Reload)
      - /usr/src/app/node_modules # Evita sobrescrever node_modules do container
    environment:
      # IMPORTANTE: Dentro do docker, o host do banco é o nome do serviço abaixo ('db')
      - DATABASE_URL=postgresql://admin:admin@db:5432/condostock?schema=public
    depends_on:
      - db
    command: npm run start:dev   # Garante que rode o comando de dev

  # Serviço do Banco de Dados
  db:
    image: postgres:15
    container_name: condostock_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: condostock
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: